version: '3.7'

services:
  keycloakdb:
    image: postgres
    ports:
      - '65350:5432'
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    volumes:
      - keycloak-data:/var/lib/postgresql/data
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    environment:
      KC_DB: postgres
      KC_DB_URL_HOST: keycloakdb
      KC_DB_URL_DATABASE: keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    ports:
      - '3881:8080'
    command:
      - start-dev
    depends_on:
      - keycloakdb

  recipemanagement-db:
    image: postgres
    restart: always
    ports:
      - '65298:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_recipemanagement
    volumes:
      - recipemanagement-data:/var/lib/postgresql/data

  rmq-message-broker:
    image: masstransit/rabbitmq
    restart: always
    ports:
      - '65302:15672' # RabbitMQ Management UI
      - '65301:5672' # RabbitMQ Broker
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest


  jaeger:
    image: jaegertracing/all-in-one:latest
#    port mappings: https://www.jaegertracing.io/docs/1.32/getting-started/
    ports:
      - "65312:5775/udp"
      - "65311:6831/udp"
      - "65313:6832/udp"
      - "65314:5778"
      - "65315:16686"
      - "65316:14250"
      - "65317:14268"
      - "65318:14269"
      - "65319:9411"

        
volumes:
  # compose volumes marker - do not delete
  keycloak-data:
  recipemanagement-data:
