version: '3.7'

services:
  recipemanagement-db:
    image: postgres
    restart: always
    ports:
      - '65298:5432'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: dev_recipemanagement
    volumes:
      - recipemanagement-data:/var/lib/postgresql/data
        
volumes:
  # compose volumes marker - do not delete
  recipemanagement-data:
